#!/bin/sh

# load X11 config
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -r "$f" ] && . "$f"
    done
    unset f
fi

# load custom config
if [ -d "$XDG_CONFIG_HOME/xorg/xinitrc.d" ]; then
    for f in "$XDG_CONFIG_HOME/xorg/xinitrc.d"/?* ; do
        [ -r "$f" ] && . "$f"
    done
    unset f
fi

# Disable beep
xset b off

# Set monitor timeout
xset -dpms
xset s off

# Set wallpaper
xwallpaper --zoom "$XDG_DATA_HOME/wallpaper.jpg" --daemon &

# Initialize X's resource database
[ -r "$XDG_CONFIG_HOME/xorg/Xresources" ] && xrdb -merge "$XDG_CONFIG_HOME/xorg/Xresources"

# spawn compositing manager
compton &

# Removes mouse cursor if it did not move for 5 seconds
unclutter &

# Synchronize all clipboards
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Greenclip clipboard manager
greenclip daemon &

eval "$(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
export SSH_AUTH_SOCK

# Blocking call to amixer. Speeds up polybar startup time and avoids that
# programs don't show up in the system tray
amixer > /dev/null

# finally start a window manager
exec i3
