#!/usr/bin/env python3
# Copyright (C) 2022 Woefe

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
from time import sleep

CPU_COUNT = os.cpu_count()
prev_idle = 0
prev_total = 0

stat_fd = open("/proc/stat")
freq_fds = [
    open(f"/sys/devices/system/cpu/cpu{cpu}/cpufreq/scaling_cur_freq")
    for cpu in range(CPU_COUNT)
]


def read_freqs():
    for fd in freq_fds:
        fd.seek(0)
        yield int(fd.readline()) / 1000000


def cpuload():
    global prev_idle
    global prev_total

    stat_fd.seek(0)
    times = list(map(int, stat_fd.readline()[5:].split(" ")))

    total_time = sum(times)
    idle_time = times[3]
    delta_total = total_time - prev_total
    delta_idle = idle_time - prev_idle
    usage = 100 * (1 - delta_idle / delta_total)
    prev_idle = idle_time
    prev_total = total_time

    load_avg = os.getloadavg()

    clazz = "high" if load_avg[0] > CPU_COUNT or usage > 90 else "normal"
    text = f" {usage:0.2f}%<b> ⋅ </b>{load_avg[0]:0.2f} {load_avg[1]:0.2f} {load_avg[2]:0.2f}"
    tooltip = "\\n".join(f"{'CPU' + str(i):>5}: {freq:0.2f} GHz" for i, freq in enumerate(read_freqs()))

    print(f'{{"text": "{text}", "tooltip": "{tooltip}", "class": "{clazz}"}}', flush=True)


while True:
    cpuload()
    sleep(2)
