#!/usr/bin/env bash

set -o errexit
set -o pipefail

git status --branch --porcelain=v2 2>&1 | awk '
BEGIN {
    fatal = 0;
    oid = "";
    head = "";
    ahead = 0;
    behind = 0;
    untracked = 0;
    unmerged = 0;
    staged = 0;
    unstaged = 0;

    RED = "%F{red}"
    MAGENTA = "%F{magenta}"
    GREEN = "%F{green}"
    BLUE = "%F{blue}"
    BOLD = "%B"
    NB = "%b"
    NC = "%f"
}

$1 == "fatal:" {
    fatal = 1;
}

$2 == "branch.oid" {
    oid = $3;
}

$2 == "branch.head" {
    head = $3;
}

$2 == "branch.ab" {
    ahead = $3;
    behind = $4;
}

$1 == "?" {
    ++untracked;
}

$1 == "u" {
    ++unmerged;
}

$1 == "1" || $1 == "2" {
    split($2, arr, "");
    if (arr[1] != ".") {
        ++staged;
    }
    if (arr[2] != ".") {
        ++unstaged;
    }
}

END {
    if (fatal == 1) {
        exit(1);
    }

    printf "[";

    printf "%s", MAGENTA
    printf "%s", BOLD
    if (head == "(detached)") {
        printf ":%s", substr(oid, 0, 7);
    } else {
        printf "%s", head;
    }
    printf "%s", NB
    printf "%s", NC

    if (behind > 0) {
        printf "↓%d", behind;
    }

    if (ahead > 0) {
        printf "↑%d", ahead;
    }

    printf "|";

    if (unmerged > 0) {
        printf "%s", RED
        printf "✖%d", unmerged;
        printf "%s", NC
    }

    if (staged > 0) {
        printf "%s", RED
        printf "●%d", staged;
        printf "%s", NC
    }

    if (unstaged > 0) {
        printf "%s", BLUE
        printf "✚%d", unstaged;
        printf "%s", NC
    }

    if (untracked > 0) {
        printf "…%d", untracked;
    }

    if (unmerged == 0 && staged == 0 && unstaged == 0 && untracked == 0) {
        printf "%s", GREEN
        printf "✔"
        printf "%s", NC
    }

    printf "] ";
}
'
